### ISSUE TITLE
Phantom Clip Skimming

### ISSUE THREAD

**Issue by sharedscene** [CommandPost/FCPCafe#241]
Apple Feedback Assistant ID: FB12929798
---

**DESCRIBE THE BUG:**
Cursor behaves as if there is a clip to skim, but there is none.

---

**TO REPRODUCE:**
Have a gap clip fill the primary storyline. Connect clips as a secondary storyline. Shuffle the order of the clips in the secondary & change where they connect, creating blank areas above the primary. The cursor skims the blank area where clips were previously placed but no longer exist.

---

**EXPECTED BEHAVIOUR:**
The clip skimmer should only ever appear when hovering over clips, not empty areas in the timeline.

---

**SCREENSHOTS:**
<img width="635" alt="phantom skimmer" src="https://github.com/CommandPost/FCPCafe/assets/105324912/1d094506-7fab-483c-8a3b-cc360cb33817">

---

**SPECS:**
- MacBook Pro / M1 Max / 64GB
- macOS Ventura 13.5
- Final Cut Pro 10.6.8

**Comment by latenitefilms** [comment]
@sharedscene - Are you able to reproduce this in Final Cut Pro 10.7?

**Comment by sharedscene** [comment]
briefly tested in 10.7 with differing variables than original filing, was not able to reproduce.
