### ISSUE TITLE
Changing Background Rendering Time

### ISSUE THREAD

**Issue by sharedscene** [CommandPost/FCPCafe#245]
**DESCRIBE THE BUG:**
Attempting to change the time for Background Rendering... CRASH.

---

**TO REPRODUCE:**
Launch Final Cut Pro, open Settings, change the time for Background Rendering... CRASH.

---

**EXPECTED BEHAVIOUR:**
Don't crash.

---

**LOGS:**
https://gist.github.com/sharedscene/0ac3d6df98de3949937c8a0db506106d
https://gist.github.com/sharedscene/8b70af72ef33d61239cb00e734a727d1
https://gist.github.com/sharedscene/949e6d86103870cac6584b57793337fb

---

**SPECS:**
- MacBook Pro / M1 Max / 64GB
- macOS Ventura 13.5
- Final Cut Pro 10.6.8

---

**ADDITIONAL COMMENTS:**
What is going on?

**Comment by latenitefilms** [comment]
I can't reproduce. Does it still crash if you don't actually have a library open?

**Comment by sharedscene** [comment]
> I can't reproduce. Does it still crash if you don't actually have a library open?

the first time, i was troubleshooting a different issue and had reset preferences. either no Library was open, or it was the default Untitled Library that it had just created.
the second & third times, after a fresh reinstall of the app, 99% sure there was no Library open when it crashed.

**Comment by latenitefilms** [comment]
@sharedscene - Are you still seeing this in Final Cut Pro 10.7?

**Comment by sharedscene** [comment]
appears to be fixed in 10.7, unable to reproduce.
