### ISSUE TITLE
Cannot Detect Blackmagic Video Monitoring Card for AV Output

### ISSUE THREAD

**Issue by FiletMyYawn** [CommandPost/FCPCafe#300]
Apple Feedback Assistant ID: FB13454447
---

**DESCRIBE THE BUG:**
Since the last release of Ventura OS, Final Cut has been unable to detect any Blackmagic video cards as an AV output option.

Interestingly, AV output is successful using Adobe Premiere, DaVinci Resolve, and Blackmagic Media Express.

This has been tested with the following:
- Clean install of latest Sonoma OS
- Newly created partition with only required software installed for testing
- Latest Final Cut
- Latest Black Magic Desktop Video, as well as all prior releases up to 12.1
- Blackmagic Decklink Mini Monitor 4K, UltraStudio 4K Mini, Decklink 8K Pro

---

**TO REPRODUCE:**
- Use M1 or above Mac with latest OS
- Use latest Final Cut
- Install Blackmagic Desktop Video software & follow instructions for Mac security settings
- Install Blackmagic Decklink or use Blackmagic UltraStudio 4K Mini with external monitor
- Try to select AV card and enable AV output from within Final Cut

---

**EXPECTED BEHAVIOUR:**
Generally, once a user installs Blackmagic Desktop Video software and sets up appropriate preferences, the option to select a Blackmagic video output card within Final Cut is available. After enabling AV output, the user is then able to successfully monitor video from a "clean" feed on an external monitor for color grading purposes. Currently, this no longer is an option as Final Cut does not detect any Blackmagic card.

---

**SPECS:**
- M1 16" MacBook Pro / M2 Ultra Mac Studio
- macOS Sonoma 14.1
- Final Cut Pro 10.7

**Comment by FiletMyYawn** [comment]
Thanks @latenitefilms , I haven't. First time seeing this. I'll definitely try it tonight. Curious though, why output still works with Premiere, DaVinci, and Blackmagic Media Express. Will reply once tested!

**Comment by FiletMyYawn** [comment]
@latenitefilms You solved it! I have been trying for nearly 2-months now to figure this out. Neither Blackmagic, nor Final Cut support could provide a solution. You're awesome, thank you so much!!!

**Comment by latenitefilms** [comment]
Clearly you don't read my Upgrade Guide, haha: https://fcp.cafe/update-guide/

Great news!
