### ISSUE TITLE
Dragging files in the Browser window to a Keyword Collection incorrectly switches projects

### ISSUE THREAD

**Issue by stevef243** [CommandPost/FCPCafe#302]
Apple Feedback Assistant ID: FB13459536
---

**DESCRIBE THE BUG:**
For instance, dragging files in the browser window to a keyword collection makes FCP switch projects, which also happens when dragging files between project or libraries.

---

**TO REPRODUCE:**
Have the browser open on the secondary screen and drag clips on the keyword collection.

---

**EXPECTED BEHAVIOUR:**
FCP to NOT select a different event afterwards

---

**SCREEN RECORDING:**
Download [here](https://drive.google.com/file/d/1lfQgv9YLvhUEbxlUM9KWuHFm3eF8glVb/view?usp=sharing).

---

**SPECS:**
- Mac Studio
- macOS Sonoma
- Final Cut Pro 10.7.x

---
**ADDITIONAL COMMENTS:**
this is going on for quite a while

**Comment by stevef243** [comment]
video issue https://drive.google.com/file/d/1lfQgv9YLvhUEbxlUM9KWuHFm3eF8glVb/view?usp=sharing

**Comment by latenitefilms** [comment]
Does this still happen in Final Cut Pro 10.7.1?

**Comment by stevef243** [comment]
not sure on holliday till early Jan

**Comment by stevef243** [comment]
This has been fixed :-)
