### ISSUE TITLE
 Accentize Plugins do not pass Audio Unit Validation on Final Cut Pro 10.7.1

### ISSUE THREAD

**Issue by muanzo** [CommandPost/FCPCafe#331]
Accentize plugins  not working  In Sonoma 14.3 and FCP X 10.7.1
![dfg](https://github.com/CommandPost/FCPCafe/assets/157735532/59ef8c51-760a-4214-b19d-1a4e5dc16322)

**Comment by latenitefilms** [comment]
Any ideas @sharedscene ?

**Comment by njbfxf** [comment]
This is not something we have been able to reproduce on our machines. Try navigating to the FCP Settings and click: Audio Units -> Validate on Next launch. Then restart the computer. If that does not help please contact FxFactory support via the FxFactory app as described here: https://fxfactory.com/support/

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, but if you're still running into issues @muanzo after chatting to FxFactory support, feel free to re-open the issue with further information. Thanks team!
