### ISSUE TITLE
HELP - Blu Ray/DVD Support Removed in 10.8 Without Warning

### ISSUE THREAD

**Issue by VoiceOfFox** [CommandPost/FCPCafe#382]
Hi, I'm new and was directed here by someone on Apple discussions.

I updated FCPX to 10.8 only to find that Blu Ray sharing has been removed without any mention in the release notes. Apple have released this article:
https://support.apple.com/en-gb/120353
It details a workaround involving using Toast 20 to burn discs from the exported project file. It even links to a page to buy Toast 20, which I did. The problem is, if the FCPX project has 5.1 audio, the audio is completely broken in the final blu ray (a known issue with no ETA on a fix, apparently!)

Now, I am by no means a pro user, probably one of small number still burning to disc. I like to make family movies from camcorder footage (which records 5.1 audio), mostly of my little boy, and share them with the wider family, who are capable of putting a disc in a player but not much else. So I'm really disappointed Apple has removed this feature, especially without warning, adding insult to injury by linking to a product that is not even fit for purpose. I left Windows for Mac to avoid this kind of thing.

So in my frantic search for this info, I've learned that I should have zipped up the previous version before updating - a simple task I didn't know was even possible, being used to how apps are installed on Windows. I don't use Time Machine because I backup my data manually and have never needed a backup of an app in 12 years of using a Mac - I've got used to everything 'just working'.

**So my question is how can I get hold of a ZIP of 10.7.1 that I can use instead of 10.8?** I would be eternally grateful if anyone can assist! A hard lesson learned!

**Comment by terrylb** [comment]
Do you have a temp email address?

**Comment by VoiceOfFox** [comment]
Hi - I have a work email I can use as I'm changing jobs next and so won't be using it after next week? Should I post it here?

**Comment by terrylb** [comment]
Yes, then remove it.

**Comment by VoiceOfFox** [comment]
Ah, gotcha. it's steve.malpass@unity3d.com. Hello again, btw!

**Comment by terrylb** [comment]
Got it. Edit the post to remove.

**Comment by latenitefilms** [comment]
Thanks @terrylb!
