### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by laurenssint** [CommandPost/FCPCafe#390]
Hi, 

Im trying to get the braw content into final cut pro.. but somehow i doing something wrong while the content is shown red window in final cut.. can somebody help me out..

**Comment by latenitefilms** [comment]
Are you using BRAW Toolbox?

**Comment by laurenssint** [comment]
Yes I do, bought it yesterday






Met vriendelijke groet,


Laurens Crans




Ter info:

Bestaande boekingen kunnen 21 dagen voor de boekingsdatum altijd kosteloos geannuleerd worden, bij annulering tussen de 21 dagen tot 14 dagen voor de boekingsdatum wordt er 15% van de uitkoopgage gerekend.
Bij annulering tussen de 14 en 7 dagen voor de boekingsdatum wordt er 25% van de uitkoopgage gerekend. Bij annulering tussen de 7 dagen tot 3 dagen voor de boekingsdatum wordt er 50% van de uitkoopgage gerekend. En bij 3 tot 0 dagen voor de boekingsdatum zal 100% van de uitkoopgage gerekend worden.
Op 21 aug 2024 om 15:26 heeft Chris Hocking ***@***.***> het volgende geschreven:﻿
Are you using BRAW Toolbox?

**Comment by latenitefilms** [comment]
What issue are you have?

**Comment by latenitefilms** [comment]
I'm going to close this for now. You can get help with BRAW Toolbox here:

https://brawtoolbox.io/support/
