### ISSUE TITLE
10.8.1 wont run - Mac Studio M1 Ultra

### ISSUE THREAD

**Issue by TristanNBaker** [CommandPost/FCPCafe#412]
Apple Feedback Assistant ID: MISSING
---

**DESCRIBE THE BUG:**
10.8.1 wont run - Mac Studio M1 Ultra. Even since it came out a few months back it has never run on my machine. I started in Sonoma with an up to date OS at the time, and kept trying the 10.8 through various updates, into sequoia, but no change.

---

**TO REPRODUCE:**
Just update the app and open it. The welcome/info screen comes up, it gets into the app, then the spinning wheel of death freezes the app.

---

**EXPECTED BEHAVIOUR:**
Same every time. Luckily I can load back on 10.7.1 and that always works flawlessly!

---

**SCREENSHOTS:**
xxx

---

**SPECS:**
- 2022 Mac Studio M1 Ultra, 128 gig ram
- macOS Sonoma 14.1.2
- Final Cut Pro 10.7.1 works - 10.8.1 does not.

---

**ADDITIONAL COMMENTS:**
I have saves reports.
From Console:

default	21:53:44.001353+1100	Final Cut Pro	CMIO_DAL_System.cpp:85:Get System unsuspended

This report had 70,791 before I said stop. That took about 10 seconds to collect that.

From activity Monitor:

Analysis of sampling Final Cut Pro (pid 45962) every 1 millisecond
Process:         Final Cut Pro [45962]
Path:            /Applications/Final Cut Pro.app/Contents/MacOS/Final Cut Pro
Load Address:    0x10418c000
Identifier:      com.apple.FinalCut
Version:         10.8.1 (421004)
Build Info:      ProEditor-42100004016000000~10
Code Type:       ARM64
Platform:        macOS
Parent Process:  launchd [1]

Date/Time:       2024-11-10 21:55:34.754 +1100
Launch Time:     2024-11-10 21:52:15.819 +1100
OS Version:      macOS 15.1 (24B83)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         2.1G
Physical footprint (peak):  2.1G
Idle exit:                  untracked
----

Call graph:
    2001 Thread_2618418   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2001 start  (in dyld) + 2840  [0x19ae48274]
    +   2001 main  (in Final Cut Pro) + 720  [0x10418facc]
    +     2001 LKApplicationMain  (in LunaKit) + 204  [0x104833780]
    +       2001 -[NSApplication run]  (in AppKit) + 480  [0x19edceae0]
    +         2001 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]  (in AppKit) + 688  [0x19f71be0c]
    +           2001 _DPSNextEvent  (in AppKit) + 660  [0x19eddba08]
    +             2001 _BlockUntilNextEventMatchingListInModeWithFilter  (in HIToolbox) + 76  [0x1a6725eb8]
    +               2001 ReceiveNextEventCommon  (in HIToolbox) + 220  [0x1a6725bb4]
    +                 2001 RunCurrentEventLoopInMode  (in HIToolbox) + 292  [0x1a671ff64]
    +                   2001 CFRunLoopRunSpecific  (in CoreFoundation) + 588  [0x19b2afbc4]
    +                     2001 __CFRunLoopRun  (in CoreFoundation) + 840  [0x19b2b05c8]
    +                       2001 __CFRunLoopDoSources0  (in CoreFoundation) + 244  [0x19b2b1a2c]
    +                         2001 __CFRunLoopDoSource0  (in CoreFoundation) + 176  [0x19b2b1cc8]
    +                           2001 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__  (in CoreFoundation) + 28  [0x19b2b1d34]
    +                             2000 __NSThreadPerformPerform  (in Foundation) + 264  [0x19c48ca80]
    +                             ! 2000 -[MIODeviceConnection updateDeviceOutputState:]  (in MIO) + 212  [0x1046ad980]
    +                             !   2000 -[MIODeviceManager updateDeviceConnnection:]  (in MIO) + 248  [0x1046b14e8]
    +                             !     1886 -[MIODeviceConnection canDoOutput]  (in MIO) + 140  [0x1046ae2f4]
    +                             !     : 1886 -[MIODeviceConnection setInputting:]  (in MIO) + 172  [0x1046adc24]
    +                             !     :   1883 CMIOObjectSetPropertyData  (in CoreMediaIO) + 604  [0x1ac90567c]
    +                             !     :   | 1882 CMIO::DAL::PlugIn::ObjectSetPropertyData(CMIO::DAL::Object const&, CMIOObjectPropertyAddress const&, unsigned int, void const*, unsigned int, void const*)  (in CoreMediaIO) + 44  [0x1ac8a5464]
    +                             !     :   | + 1882 (anonymous namespace)::HardwarePlugIn_ObjectSetPropertyData(CMIOHardwarePlugInInterface**, unsigned int, CMIOObjectPropertyAddress const*, unsigned int, void const*, unsigned int, void const*)  (in DeckLinkCMIO) + 248  [0x113e3be98]
    +                             !     :   | +   1882 DirectionControl::UpdateValue(bool, bool)  (in DeckLinkCMIO) + 72  [0x113e4b034]
    +                             !     :   | +     1837 DeckLinkDevice::CreateStreams(unsigned int)  (in DeckLinkCMIO) + 228  [0x113e4bccc]
    +                             !     :   | +     ! 1822 DeckLinkOutputStream::Initialize()  (in DeckLinkCMIO) + 56  [0x113e503a4]
    +                             !     :   | +     ! : 1459 DeckLinkOutputStream::AddAvailableFormatDescriptions()  (in DeckLinkCMIO) + 860  [0x113e50a6c]
    +                             !     :   | +     ! : | 1384 CDeckLinkOutput::DoesSupportVideoMode(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int*, bool*)  (in DeckLinkAPI) + 372  [0x35276f888]
    +                             !     :   | +     ! : | + 1383 DoesSupportVideoOutputMode  (in DeckLinkAPI) + 132  [0x352b1b2e8]
    +                             !     :   | +     ! : | + ! 1383 IOCtlProxy::writeScalarReadScalar(int, unsigned long long const*, unsigned int, unsigned long long*, unsigned int)  (in DeckLinkAPI) + 104  [0x352b21db8]
    +                             !     :   | +     ! : | + !   1375 BlackmagicIOAccessProxy::perform(IOJob::IOJob&)  (in DeckLinkAPI) + 380  [0x352b2c954]
    +                             !     :   | +     ! : | + !   : 1340 BlackmagicIOAccessProxy::performJobWithWorkaround(IOJob::IOJob&)  (in DeckLinkAPI) + 112  [0x352b2ca30]
    +                             !     :   | +     ! : | + !   : | 1339 Nativeproxy::perform(IOJob::IOJob&)  (in DeckLinkAPI) + 456  [0x352b26bd8]
    +                             !     :   | +     ! : | + !   : | + 1337 IOConnectCallMethod  (in IOKit) + 236  [0x19ec54128]
    +                             !     :   | +     ! : | + !   : | + ! 1329 io_connect_method  (in IOKit) + 524  [0x19ec54360]
    +                             !     :   | +     ! : | + !   : | + ! : 1328 mach_msg2_internal  (in libsystem_kernel.dylib) + 80  [0x19b19c5d0]
    +                             !     :   | +     ! : | + !   : | + ! : | 1328 mach_msg2_trap  (in libsystem_kernel.dylib) + 8  [0x19b189e34]
    +                             !     :   | +     ! : | + !   : | + ! : 1 DYLD-STUB$$mach_msg2_internal  (in IOKit) + 8  [0x19ed0ad10]
    +                             !     :   | +     ! : | + !   : | + ! 4 io_connect_method  (in IOKit) + 884  [0x19ec544c8]
    +                             !     :   | +     ! : | + !   : | + ! : 2 DYLD-STUB$$memcpy  (in IOKit) + 0  [0x19ed0ae18]
    +                             !     :   | +     ! : | + !   : | + ! : 2 _platform_memmove  (in libsystem_platform.dylib) + 0  [0x19b1ffdb0]
    +                             !     :   | +     ! : | + !   : | + ! 3 io_connect_method  (in IOKit) + 524,580  [0x19ec54360,0x19ec54398]
    +                             !     :   | +     ! : | + !   : | + ! 1 io_connect_method  (in IOKit) + 228  [0x19ec54238]
    +                             !     :   | +     ! : | + !   : | + !   1 DYLD-STUB$$mkdtempat_np  (in libsystem_c.dylib) + 0  [0x19b0d8b40]
    +                             !     :   | +     ! : | + !   : | + 2 IOConnectCallMethod  (in IOKit) + 0,236  [0x19ec5403c,0x19ec54128]
    +                             !     :   | +     ! : | + !   : | 1 Nativeproxy::perform(IOJob::IOJob&)  (in DeckLinkAPI) + 456  [0x352b26bd8]
    +                             !     :   | +     ! : | + !   : 17 BlackmagicIOAccessProxy::performJobWithWorkaround(IOJob::IOJob&)  (in DeckLinkAPI) + 76  [0x352b2ca0c]
  
and on and on......

**Comment by latenitefilms** [comment]
Can you try uninstalling the Blackmagic Desktop Video drivers?

**Comment by TristanNBaker** [comment]
Hey,

Yeah - Seeing all the declink mentions I just updated the software, and all my problems are gone! 
I can’t believe after so many months it was that.

Problem solved, so easily after all that.

Thank you for the Activity monitor and Console tips!


Thanks,

Tristan Baker
Bam Studios

￼

www.bamstudios.com.au
0410 635 308

**Comment by latenitefilms** [comment]
Great news!
